2023-03-15 14:27:07,178 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:27:07,179 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:27:07,179 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f117fe2a8c0>
2023-03-15 14:27:07,550 host.py INFO : Creating host esxi01.demo.local
2023-03-15 14:27:07,550 host.py INFO : Creating host esxi01.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi01:999701628:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 14:27:10,630 host.py INFO : The response is {'id': 'dbd34c53-9b74-4b53-83e3-59a3aa07bef8'}
2023-03-15 14:27:10,992 host.py INFO : Getting host dbd34c53-9b74-4b53-83e3-59a3aa07bef8 details
2023-03-15 14:27:11,287 host.py INFO : changed True
2023-03-15 14:27:11,694 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:27:11,694 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:27:11,694 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fc0969be8f0>
2023-03-15 14:27:11,991 host.py INFO : Creating host esxi02.demo.local
2023-03-15 14:27:11,991 host.py INFO : Creating host esxi02.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi02:380351444:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 14:27:13,807 host.py INFO : The response is {'id': 'bfb69d0a-084b-42f3-84e7-5caa1da0d013'}
2023-03-15 14:27:14,151 host.py INFO : Getting host bfb69d0a-084b-42f3-84e7-5caa1da0d013 details
2023-03-15 14:27:14,583 host.py INFO : changed True
2023-03-15 14:27:14,986 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:27:14,987 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:27:14,987 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f729b83e8f0>
2023-03-15 14:27:15,379 host.py INFO : Creating host esxi03.demo.local
2023-03-15 14:27:15,380 host.py INFO : Creating host esxi03.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi03:2135904199:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 14:27:16,956 host.py INFO : The response is {'id': 'bd84ed32-e7b4-41c6-90ef-a9128d355f7d'}
2023-03-15 14:27:17,236 host.py INFO : Getting host bd84ed32-e7b4-41c6-90ef-a9128d355f7d details
2023-03-15 14:27:17,573 host.py INFO : changed True
2023-03-15 14:27:18,177 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:27:18,177 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:27:18,178 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f49f772e890>
2023-03-15 14:27:18,780 hostgroup.py INFO : Creating host group esx_datastore
2023-03-15 14:27:18,781 hostgroup.py INFO : Creating host group esx_datastore with hosts ['dbd34c53-9b74-4b53-83e3-59a3aa07bef8']
2023-03-15 14:27:21,759 hostgroup.py INFO : the response is {'id': '734fcd55-9726-433c-ab5c-401d25de451e'}
2023-03-15 14:27:22,049 hostgroup.py INFO : Getting host group 734fcd55-9726-433c-ab5c-401d25de451e details
2023-03-15 14:27:22,420 hostgroup.py INFO : changed True
2023-03-15 14:27:22,827 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:27:22,827 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:27:22,827 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fd3d103a890>
2023-03-15 14:27:23,101 hostgroup.py INFO : Getting host group 734fcd55-9726-433c-ab5c-401d25de451e details
2023-03-15 14:27:23,726 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 14:27:23,726 hostgroup.py INFO : existing hosts ['dbd34c53-9b74-4b53-83e3-59a3aa07bef8']
2023-03-15 14:27:23,726 hostgroup.py INFO : Adding hosts ['bfb69d0a-084b-42f3-84e7-5caa1da0d013'] to host group esx_datastore
2023-03-15 14:27:25,575 hostgroup.py INFO : Getting host group 734fcd55-9726-433c-ab5c-401d25de451e details
2023-03-15 14:27:26,246 hostgroup.py INFO : changed True
2023-03-15 14:27:26,653 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:27:26,653 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:27:26,653 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fdecb1e2890>
2023-03-15 14:27:26,939 hostgroup.py INFO : Getting host group 734fcd55-9726-433c-ab5c-401d25de451e details
2023-03-15 14:27:27,603 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 14:27:27,603 hostgroup.py INFO : existing hosts ['dbd34c53-9b74-4b53-83e3-59a3aa07bef8', 'bfb69d0a-084b-42f3-84e7-5caa1da0d013']
2023-03-15 14:27:27,603 hostgroup.py INFO : Adding hosts ['bd84ed32-e7b4-41c6-90ef-a9128d355f7d'] to host group esx_datastore
2023-03-15 14:27:30,022 hostgroup.py INFO : Getting host group 734fcd55-9726-433c-ab5c-401d25de451e details
2023-03-15 14:27:30,339 hostgroup.py INFO : changed True
2023-03-15 14:27:31,078 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:27:31,078 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:27:31,078 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fc32b58e9b0>
2023-03-15 14:27:31,763 volume.py INFO : Creating volume esx_vol of size 858993459200 with performance policy None, protection_policy None, description DTW ESXi DataStore and volume_group None
2023-03-15 14:27:33,300 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 14:27:33,300 volume.py INFO : Mapping volume esx_vol to hostgroup esx_datastore with HLU None
2023-03-15 14:27:34,513 volume.py INFO : Getting volume snapshots
2023-03-15 14:30:21,254 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:30:21,254 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:30:21,254 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f069331e8f0>
2023-03-15 14:30:21,674 host.py INFO : Getting host dbd34c53-9b74-4b53-83e3-59a3aa07bef8 details
2023-03-15 14:30:22,011 host.py INFO : Adding initiators to host dbd34c53-9b74-4b53-83e3-59a3aa07bef8
2023-03-15 14:30:22,011 host.py INFO : Initiators are already present in host esxi01.demo.local
2023-03-15 14:30:22,011 host.py INFO : Getting host dbd34c53-9b74-4b53-83e3-59a3aa07bef8 details
2023-03-15 14:30:22,313 host.py INFO : changed False
2023-03-15 14:30:22,735 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:30:22,735 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:30:22,736 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f760ba668f0>
2023-03-15 14:30:23,017 host.py INFO : Getting host bfb69d0a-084b-42f3-84e7-5caa1da0d013 details
2023-03-15 14:30:23,276 host.py INFO : Adding initiators to host bfb69d0a-084b-42f3-84e7-5caa1da0d013
2023-03-15 14:30:23,276 host.py INFO : Initiators are already present in host esxi02.demo.local
2023-03-15 14:30:23,276 host.py INFO : Getting host bfb69d0a-084b-42f3-84e7-5caa1da0d013 details
2023-03-15 14:30:23,614 host.py INFO : changed False
2023-03-15 14:30:24,020 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:30:24,020 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:30:24,020 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fe27e0068f0>
2023-03-15 14:30:24,288 host.py INFO : Getting host bd84ed32-e7b4-41c6-90ef-a9128d355f7d details
2023-03-15 14:30:24,541 host.py INFO : Adding initiators to host bd84ed32-e7b4-41c6-90ef-a9128d355f7d
2023-03-15 14:30:24,541 host.py INFO : Initiators are already present in host esxi03.demo.local
2023-03-15 14:30:24,541 host.py INFO : Getting host bd84ed32-e7b4-41c6-90ef-a9128d355f7d details
2023-03-15 14:30:24,825 host.py INFO : changed False
2023-03-15 14:30:25,444 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:30:25,444 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:30:25,444 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f476d58a890>
2023-03-15 14:30:25,723 hostgroup.py INFO : Getting host group 734fcd55-9726-433c-ab5c-401d25de451e details
2023-03-15 14:30:26,279 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 14:30:26,279 hostgroup.py INFO : existing hosts ['dbd34c53-9b74-4b53-83e3-59a3aa07bef8', 'bfb69d0a-084b-42f3-84e7-5caa1da0d013', 'bd84ed32-e7b4-41c6-90ef-a9128d355f7d']
2023-03-15 14:30:26,279 hostgroup.py INFO : Hosts are already present in host group esx_datastore
2023-03-15 14:30:26,279 hostgroup.py INFO : Getting host group 734fcd55-9726-433c-ab5c-401d25de451e details
2023-03-15 14:30:26,602 hostgroup.py INFO : changed False
2023-03-15 14:30:27,029 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:30:27,029 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:30:27,029 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f4924cee890>
2023-03-15 14:30:27,326 hostgroup.py INFO : Getting host group 734fcd55-9726-433c-ab5c-401d25de451e details
2023-03-15 14:30:28,221 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 14:30:28,222 hostgroup.py INFO : existing hosts ['dbd34c53-9b74-4b53-83e3-59a3aa07bef8', 'bfb69d0a-084b-42f3-84e7-5caa1da0d013', 'bd84ed32-e7b4-41c6-90ef-a9128d355f7d']
2023-03-15 14:30:28,222 hostgroup.py INFO : Hosts are already present in host group esx_datastore
2023-03-15 14:30:28,222 hostgroup.py INFO : Getting host group 734fcd55-9726-433c-ab5c-401d25de451e details
2023-03-15 14:30:28,908 hostgroup.py INFO : changed False
2023-03-15 14:30:29,327 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:30:29,327 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:30:29,327 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fb60cfb2890>
2023-03-15 14:30:29,978 hostgroup.py INFO : Getting host group 734fcd55-9726-433c-ab5c-401d25de451e details
2023-03-15 14:30:30,607 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 14:30:30,608 hostgroup.py INFO : existing hosts ['dbd34c53-9b74-4b53-83e3-59a3aa07bef8', 'bfb69d0a-084b-42f3-84e7-5caa1da0d013', 'bd84ed32-e7b4-41c6-90ef-a9128d355f7d']
2023-03-15 14:30:30,608 hostgroup.py INFO : Hosts are already present in host group esx_datastore
2023-03-15 14:30:30,608 hostgroup.py INFO : Getting host group 734fcd55-9726-433c-ab5c-401d25de451e details
2023-03-15 14:30:30,937 hostgroup.py INFO : changed False
2023-03-15 14:30:31,604 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:30:31,605 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:30:31,605 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f779b7ae9b0>
2023-03-15 14:30:32,314 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 14:30:32,314 volume.py INFO : Volume esx_vol is already mapped to hostgroup esx_datastore
2023-03-15 14:30:32,744 volume.py INFO : Getting volume snapshots
2023-03-15 14:30:55,973 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:30:55,973 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:30:55,974 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f69688169b0>
2023-03-15 14:30:56,682 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 14:30:56,682 volume.py INFO : Volume esx_vol is already mapped to hostgroup esx_datastore
2023-03-15 14:30:57,085 volume.py INFO : Getting volume snapshots
2023-03-15 14:31:28,361 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:31:28,361 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:31:28,361 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f3eaf5929b0>
2023-03-15 14:31:29,655 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 14:31:29,655 volume.py INFO : Unmapping volume esx_vol from hostgroup esx_datastore
2023-03-15 14:31:30,688 volume.py INFO : Getting volume snapshots
2023-03-15 14:31:31,368 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:31:31,368 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:31:31,368 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f5e024f29b0>
2023-03-15 14:31:32,140 volume.py INFO : Deleting volume esx_vol 
2023-03-15 14:31:32,140 volume.py INFO : Deleting volume esx_vol
2023-03-15 14:31:33,481 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:31:33,481 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:31:33,481 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f331fd56890>
2023-03-15 14:31:33,849 hostgroup.py INFO : Getting host group 734fcd55-9726-433c-ab5c-401d25de451e details
2023-03-15 14:31:34,153 hostgroup.py INFO : Deleting host group esx_datastore 
2023-03-15 14:31:35,719 hostgroup.py INFO : changed True
2023-03-15 14:31:36,352 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:31:36,352 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:31:36,352 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fda14efe8f0>
2023-03-15 14:31:36,712 host.py INFO : changed False
2023-03-15 14:31:37,143 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:31:37,144 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:31:37,144 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f43972c28f0>
2023-03-15 14:31:37,424 host.py INFO : changed False
2023-03-15 14:31:37,830 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:31:37,831 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:31:37,831 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f1164fea8f0>
2023-03-15 14:31:38,149 host.py INFO : changed False
2023-03-15 14:33:08,470 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:33:08,471 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:33:08,471 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fdea9ba28c0>
2023-03-15 14:33:08,941 host.py INFO : Creating host esxi01.demo.local
2023-03-15 14:33:08,941 host.py INFO : Creating host esxi01.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi01:999701628:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 14:33:10,815 host.py INFO : The response is {'id': 'ae9eb6c1-a830-44db-98f5-f252d8973073'}
2023-03-15 14:33:11,121 host.py INFO : Getting host ae9eb6c1-a830-44db-98f5-f252d8973073 details
2023-03-15 14:33:11,398 host.py INFO : changed True
2023-03-15 14:33:11,814 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:33:11,814 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:33:11,814 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f3e246d68f0>
2023-03-15 14:33:12,083 host.py INFO : Creating host esxi02.demo.local
2023-03-15 14:33:12,083 host.py INFO : Creating host esxi02.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi02:380351444:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 14:33:13,971 host.py INFO : The response is {'id': 'd0aa43cb-e06e-4682-b0b3-434e8c2c4d9c'}
2023-03-15 14:33:14,375 host.py INFO : Getting host d0aa43cb-e06e-4682-b0b3-434e8c2c4d9c details
2023-03-15 14:33:14,735 host.py INFO : changed True
2023-03-15 14:33:15,187 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:33:15,188 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:33:15,188 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fef32fe68f0>
2023-03-15 14:33:15,494 host.py INFO : Creating host esxi03.demo.local
2023-03-15 14:33:15,494 host.py INFO : Creating host esxi03.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi03:2135904199:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 14:33:17,087 host.py INFO : The response is {'id': '0e847579-1523-4925-9434-d74997bf9b1e'}
2023-03-15 14:33:17,452 host.py INFO : Getting host 0e847579-1523-4925-9434-d74997bf9b1e details
2023-03-15 14:33:17,795 host.py INFO : changed True
2023-03-15 14:33:18,402 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:33:18,403 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:33:18,403 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f28fe4d2890>
2023-03-15 14:33:19,267 hostgroup.py INFO : Creating host group esx_datastore
2023-03-15 14:33:19,268 hostgroup.py INFO : Creating host group esx_datastore with hosts ['ae9eb6c1-a830-44db-98f5-f252d8973073']
2023-03-15 14:33:22,621 hostgroup.py INFO : the response is {'id': '6543c2cc-80c5-4fc4-b886-2870c4b9d0ee'}
2023-03-15 14:33:23,294 hostgroup.py INFO : Getting host group 6543c2cc-80c5-4fc4-b886-2870c4b9d0ee details
2023-03-15 14:33:23,711 hostgroup.py INFO : changed True
2023-03-15 14:33:24,180 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:33:24,180 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:33:24,180 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fb0aa0e2890>
2023-03-15 14:33:24,495 hostgroup.py INFO : Getting host group 6543c2cc-80c5-4fc4-b886-2870c4b9d0ee details
2023-03-15 14:33:25,547 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 14:33:25,547 hostgroup.py INFO : existing hosts ['ae9eb6c1-a830-44db-98f5-f252d8973073']
2023-03-15 14:33:25,548 hostgroup.py INFO : Adding hosts ['d0aa43cb-e06e-4682-b0b3-434e8c2c4d9c'] to host group esx_datastore
2023-03-15 14:33:28,255 hostgroup.py INFO : Getting host group 6543c2cc-80c5-4fc4-b886-2870c4b9d0ee details
2023-03-15 14:33:28,633 hostgroup.py INFO : changed True
2023-03-15 14:33:29,046 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:33:29,046 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:33:29,046 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f542674a890>
2023-03-15 14:33:29,333 hostgroup.py INFO : Getting host group 6543c2cc-80c5-4fc4-b886-2870c4b9d0ee details
2023-03-15 14:33:29,934 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 14:33:29,935 hostgroup.py INFO : existing hosts ['ae9eb6c1-a830-44db-98f5-f252d8973073', 'd0aa43cb-e06e-4682-b0b3-434e8c2c4d9c']
2023-03-15 14:33:29,935 hostgroup.py INFO : Adding hosts ['0e847579-1523-4925-9434-d74997bf9b1e'] to host group esx_datastore
2023-03-15 14:33:31,710 hostgroup.py INFO : Getting host group 6543c2cc-80c5-4fc4-b886-2870c4b9d0ee details
2023-03-15 14:33:32,021 hostgroup.py INFO : changed True
2023-03-15 14:33:32,709 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:33:32,709 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:33:32,709 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7febf404a9b0>
2023-03-15 14:33:33,416 volume.py INFO : Creating volume esx_vol of size 858993459200 with performance policy None, protection_policy None, description DTW ESXi DataStore and volume_group None
2023-03-15 14:33:35,341 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 14:33:35,341 volume.py INFO : Mapping volume esx_vol to hostgroup esx_datastore with HLU None
2023-03-15 14:33:37,091 volume.py INFO : Getting volume snapshots
2023-03-15 14:46:45,778 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:46:45,778 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:46:45,778 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f4349d829b0>
2023-03-15 14:46:45,913 volume.py ERROR : Get host group: esx_datastore failed with error: HTTP code: 401, Unauthorized [Access forbidden: Authentication required.]
2023-03-15 14:49:09,615 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:49:09,615 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:49:09,615 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f4076d1e980>
2023-03-15 14:49:09,728 volume.py ERROR : Get host group: esx_datastore failed with error: HTTP code: 401, Unauthorized [Access forbidden: Authentication required.]
2023-03-15 14:50:06,450 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:50:06,450 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:50:06,450 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f1578056ad0>
2023-03-15 14:50:07,447 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 14:50:07,447 volume.py INFO : Volume esx_vol is already mapped to hostgroup esx_datastore
2023-03-15 14:50:08,063 volume.py INFO : Getting volume snapshots
2023-03-15 14:50:45,187 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:50:45,187 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:50:45,187 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f4fe6586b00>
2023-03-15 14:50:46,233 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 14:50:46,233 volume.py INFO : Unmapping volume esx_vol from hostgroup esx_datastore
2023-03-15 14:50:47,494 volume.py INFO : Getting volume snapshots
2023-03-15 14:50:48,142 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:50:48,143 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:50:48,143 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f0c3b376b00>
2023-03-15 14:50:49,034 volume.py INFO : Deleting volume esx_vol 
2023-03-15 14:50:49,034 volume.py INFO : Deleting volume esx_vol
2023-03-15 14:50:50,349 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:50:50,349 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:50:50,350 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fed5e0369e0>
2023-03-15 14:50:50,645 hostgroup.py INFO : Getting host group 6543c2cc-80c5-4fc4-b886-2870c4b9d0ee details
2023-03-15 14:50:51,096 hostgroup.py INFO : Deleting host group esx_datastore 
2023-03-15 14:50:54,131 hostgroup.py INFO : changed True
2023-03-15 14:50:54,739 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:50:54,739 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:50:54,739 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fd3b30d2a40>
2023-03-15 14:50:55,112 host.py INFO : changed False
2023-03-15 14:50:55,510 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:50:55,510 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:50:55,510 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f47b50b6a40>
2023-03-15 14:50:55,819 host.py INFO : changed False
2023-03-15 14:50:56,223 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:50:56,223 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:50:56,223 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f84b5a42a40>
2023-03-15 14:50:56,489 host.py INFO : changed False
2023-03-15 14:51:39,343 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:51:39,344 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:51:39,344 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7ff229666a40>
2023-03-15 14:51:39,845 host.py INFO : Creating host esxi01.demo.local
2023-03-15 14:51:39,845 host.py INFO : Creating host esxi01.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi01:999701628:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 14:51:41,553 host.py INFO : The response is {'id': '0a06189a-b925-41d1-a14f-92adc51ed348'}
2023-03-15 14:51:41,856 host.py INFO : Getting host 0a06189a-b925-41d1-a14f-92adc51ed348 details
2023-03-15 14:51:42,164 host.py INFO : changed True
2023-03-15 14:51:42,577 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:51:42,577 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:51:42,578 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fbe2facaa40>
2023-03-15 14:51:42,906 host.py INFO : Creating host esxi02.demo.local
2023-03-15 14:51:42,906 host.py INFO : Creating host esxi02.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi02:380351444:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 14:51:44,274 host.py INFO : The response is {'id': '1eacb6c8-5843-414c-934d-a3aa7467f21c'}
2023-03-15 14:51:44,525 host.py INFO : Getting host 1eacb6c8-5843-414c-934d-a3aa7467f21c details
2023-03-15 14:51:44,860 host.py INFO : changed True
2023-03-15 14:51:45,252 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:51:45,253 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:51:45,253 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fbcb1bfaa40>
2023-03-15 14:51:45,737 host.py INFO : Creating host esxi03.demo.local
2023-03-15 14:51:45,738 host.py INFO : Creating host esxi03.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi03:2135904199:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 14:51:47,126 host.py INFO : The response is {'id': '3c6cb02f-2ca3-4420-bfd2-aee19f629c63'}
2023-03-15 14:51:47,433 host.py INFO : Getting host 3c6cb02f-2ca3-4420-bfd2-aee19f629c63 details
2023-03-15 14:51:47,855 host.py INFO : changed True
2023-03-15 14:51:48,456 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:51:48,456 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:51:48,456 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fc613b269e0>
2023-03-15 14:51:48,956 hostgroup.py INFO : Creating host group esx_datastore
2023-03-15 14:51:48,957 hostgroup.py INFO : Creating host group esx_datastore with hosts ['0a06189a-b925-41d1-a14f-92adc51ed348']
2023-03-15 14:51:51,657 hostgroup.py INFO : the response is {'id': 'c62bec61-2848-4488-ad64-dbf1e98195e1'}
2023-03-15 14:51:51,940 hostgroup.py INFO : Getting host group c62bec61-2848-4488-ad64-dbf1e98195e1 details
2023-03-15 14:51:52,206 hostgroup.py INFO : changed True
2023-03-15 14:51:52,634 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:51:52,635 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:51:52,635 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fcdc024a9e0>
2023-03-15 14:51:52,931 hostgroup.py INFO : Getting host group c62bec61-2848-4488-ad64-dbf1e98195e1 details
2023-03-15 14:51:53,941 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 14:51:53,941 hostgroup.py INFO : existing hosts ['0a06189a-b925-41d1-a14f-92adc51ed348']
2023-03-15 14:51:53,942 hostgroup.py INFO : Adding hosts ['1eacb6c8-5843-414c-934d-a3aa7467f21c'] to host group esx_datastore
2023-03-15 14:51:56,180 hostgroup.py INFO : Getting host group c62bec61-2848-4488-ad64-dbf1e98195e1 details
2023-03-15 14:51:56,440 hostgroup.py INFO : changed True
2023-03-15 14:51:56,860 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:51:56,860 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:51:56,860 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f34523c69e0>
2023-03-15 14:51:57,181 hostgroup.py INFO : Getting host group c62bec61-2848-4488-ad64-dbf1e98195e1 details
2023-03-15 14:51:57,724 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 14:51:57,724 hostgroup.py INFO : existing hosts ['0a06189a-b925-41d1-a14f-92adc51ed348', '1eacb6c8-5843-414c-934d-a3aa7467f21c']
2023-03-15 14:51:57,724 hostgroup.py INFO : Adding hosts ['3c6cb02f-2ca3-4420-bfd2-aee19f629c63'] to host group esx_datastore
2023-03-15 14:51:59,719 hostgroup.py INFO : Getting host group c62bec61-2848-4488-ad64-dbf1e98195e1 details
2023-03-15 14:52:00,214 hostgroup.py INFO : changed True
2023-03-15 14:52:00,860 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:52:00,861 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:52:00,861 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f4c39df6ad0>
2023-03-15 14:52:01,929 volume.py INFO : Creating volume esx_vol of size 858993459200 with performance policy None, protection_policy None, description DTW ESXi DataStore and volume_group None
2023-03-15 14:52:03,518 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 14:52:03,518 volume.py INFO : Mapping volume esx_vol to hostgroup esx_datastore with HLU None
2023-03-15 14:52:05,225 volume.py INFO : Getting volume snapshots
2023-03-15 14:56:07,013 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:56:07,013 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:56:07,013 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f6743ecead0>
2023-03-15 14:56:08,116 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 14:56:08,116 volume.py INFO : Volume esx_vol is already mapped to hostgroup esx_datastore
2023-03-15 14:56:08,597 volume.py INFO : Getting volume snapshots
2023-03-15 14:56:40,180 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:56:40,181 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:56:40,181 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fbfc45aab00>
2023-03-15 14:56:41,364 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 14:56:41,364 volume.py INFO : Unmapping volume esx_vol from hostgroup esx_datastore
2023-03-15 14:56:42,395 volume.py INFO : Getting volume snapshots
2023-03-15 14:56:43,043 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:56:43,043 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:56:43,043 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7ff9f9cfab00>
2023-03-15 14:56:44,703 volume.py INFO : Deleting volume esx_vol 
2023-03-15 14:56:44,703 volume.py INFO : Deleting volume esx_vol
2023-03-15 14:56:46,333 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:56:46,333 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:56:46,333 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f45a5c2a9e0>
2023-03-15 14:56:46,678 hostgroup.py INFO : Getting host group c62bec61-2848-4488-ad64-dbf1e98195e1 details
2023-03-15 14:56:46,953 hostgroup.py INFO : Deleting host group esx_datastore 
2023-03-15 14:56:48,874 hostgroup.py INFO : changed True
2023-03-15 14:56:49,582 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:56:49,582 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:56:49,582 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f175becea40>
2023-03-15 14:56:49,919 host.py INFO : changed False
2023-03-15 14:56:50,349 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:56:50,349 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:56:50,350 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f221ed4ea40>
2023-03-15 14:56:51,066 host.py INFO : changed False
2023-03-15 14:56:51,500 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:56:51,500 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:56:51,501 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f175571aa40>
2023-03-15 14:56:51,961 host.py INFO : changed False
2023-03-15 14:58:13,440 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:58:13,440 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:58:13,440 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f3088ad6a40>
2023-03-15 14:58:13,826 host.py INFO : Creating host esxi01.demo.local
2023-03-15 14:58:13,826 host.py INFO : Creating host esxi01.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi01:999701628:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 14:58:15,553 host.py INFO : The response is {'id': '9cf2d0d8-6b80-4730-a39d-61643f2449d9'}
2023-03-15 14:58:15,869 host.py INFO : Getting host 9cf2d0d8-6b80-4730-a39d-61643f2449d9 details
2023-03-15 14:58:16,198 host.py INFO : changed True
2023-03-15 14:58:16,616 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:58:16,616 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:58:16,616 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f03ab002a40>
2023-03-15 14:58:16,968 host.py INFO : Creating host esxi02.demo.local
2023-03-15 14:58:16,968 host.py INFO : Creating host esxi02.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi02:380351444:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 14:58:18,681 host.py INFO : The response is {'id': '2adaa1ce-a480-4383-a78a-169b86d41a14'}
2023-03-15 14:58:19,150 host.py INFO : Getting host 2adaa1ce-a480-4383-a78a-169b86d41a14 details
2023-03-15 14:58:19,488 host.py INFO : changed True
2023-03-15 14:58:19,922 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:58:19,922 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:58:19,922 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f36a55a6a40>
2023-03-15 14:58:20,388 host.py INFO : Creating host esxi03.demo.local
2023-03-15 14:58:20,389 host.py INFO : Creating host esxi03.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi03:2135904199:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 14:58:22,110 host.py INFO : The response is {'id': '643e9580-f194-46c8-b5d4-b92a1033b33d'}
2023-03-15 14:58:22,432 host.py INFO : Getting host 643e9580-f194-46c8-b5d4-b92a1033b33d details
2023-03-15 14:58:22,962 host.py INFO : changed True
2023-03-15 14:58:23,817 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:58:23,818 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:58:23,818 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f2a0e9829e0>
2023-03-15 14:58:24,550 hostgroup.py INFO : Creating host group esx_datastore
2023-03-15 14:58:24,551 hostgroup.py INFO : Creating host group esx_datastore with hosts ['9cf2d0d8-6b80-4730-a39d-61643f2449d9']
2023-03-15 14:58:27,491 hostgroup.py INFO : the response is {'id': '2e306e3a-d61f-4d29-889e-2cb220fbc143'}
2023-03-15 14:58:27,803 hostgroup.py INFO : Getting host group 2e306e3a-d61f-4d29-889e-2cb220fbc143 details
2023-03-15 14:58:28,138 hostgroup.py INFO : changed True
2023-03-15 14:58:28,544 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:58:28,544 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:58:28,544 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f44a91969e0>
2023-03-15 14:58:28,836 hostgroup.py INFO : Getting host group 2e306e3a-d61f-4d29-889e-2cb220fbc143 details
2023-03-15 14:58:29,446 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 14:58:29,446 hostgroup.py INFO : existing hosts ['9cf2d0d8-6b80-4730-a39d-61643f2449d9']
2023-03-15 14:58:29,446 hostgroup.py INFO : Adding hosts ['2adaa1ce-a480-4383-a78a-169b86d41a14'] to host group esx_datastore
2023-03-15 14:58:31,589 hostgroup.py INFO : Getting host group 2e306e3a-d61f-4d29-889e-2cb220fbc143 details
2023-03-15 14:58:31,895 hostgroup.py INFO : changed True
2023-03-15 14:58:32,285 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:58:32,285 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:58:32,285 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f4b7d7f69e0>
2023-03-15 14:58:32,609 hostgroup.py INFO : Getting host group 2e306e3a-d61f-4d29-889e-2cb220fbc143 details
2023-03-15 14:58:33,366 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 14:58:33,366 hostgroup.py INFO : existing hosts ['9cf2d0d8-6b80-4730-a39d-61643f2449d9', '2adaa1ce-a480-4383-a78a-169b86d41a14']
2023-03-15 14:58:33,366 hostgroup.py INFO : Adding hosts ['643e9580-f194-46c8-b5d4-b92a1033b33d'] to host group esx_datastore
2023-03-15 14:58:35,858 hostgroup.py INFO : Getting host group 2e306e3a-d61f-4d29-889e-2cb220fbc143 details
2023-03-15 14:58:36,174 hostgroup.py INFO : changed True
2023-03-15 14:58:36,756 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:58:36,756 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:58:36,756 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fbbff9d6b00>
2023-03-15 14:58:37,317 volume.py INFO : Creating volume esx_vol of size 858993459200 with performance policy None, protection_policy None, description DTW ESXi DataStore and volume_group None
2023-03-15 14:58:38,981 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 14:58:38,982 volume.py INFO : Mapping volume esx_vol to hostgroup esx_datastore with HLU None
2023-03-15 14:58:40,338 volume.py INFO : Getting volume snapshots
2023-03-15 14:59:39,067 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 14:59:39,067 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 14:59:39,067 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f6611d56b00>
2023-03-15 14:59:39,843 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 14:59:39,844 volume.py INFO : Volume esx_vol is already mapped to hostgroup esx_datastore
2023-03-15 14:59:40,635 volume.py INFO : Getting volume snapshots
2023-03-15 15:00:12,704 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:00:12,704 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:00:12,704 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f095a3aaad0>
2023-03-15 15:00:13,555 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 15:00:13,555 volume.py INFO : Unmapping volume esx_vol from hostgroup esx_datastore
2023-03-15 15:00:15,287 volume.py INFO : Getting volume snapshots
2023-03-15 15:00:15,862 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:00:15,862 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:00:15,862 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f71fadeead0>
2023-03-15 15:00:16,755 volume.py INFO : Deleting volume esx_vol 
2023-03-15 15:00:16,755 volume.py INFO : Deleting volume esx_vol
2023-03-15 15:00:17,894 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:00:17,894 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:00:17,895 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f6f6e0f29b0>
2023-03-15 15:00:18,149 hostgroup.py INFO : Getting host group 2e306e3a-d61f-4d29-889e-2cb220fbc143 details
2023-03-15 15:00:18,412 hostgroup.py INFO : Deleting host group esx_datastore 
2023-03-15 15:00:20,142 hostgroup.py INFO : changed True
2023-03-15 15:00:20,729 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:00:20,729 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:00:20,729 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f2a61852a10>
2023-03-15 15:00:21,041 host.py INFO : changed False
2023-03-15 15:00:21,468 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:00:21,469 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:00:21,469 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f196b7d6a10>
2023-03-15 15:00:21,795 host.py INFO : changed False
2023-03-15 15:00:22,205 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:00:22,205 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:00:22,205 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f38c1f22a10>
2023-03-15 15:00:22,474 host.py INFO : changed False
2023-03-15 15:00:39,139 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:00:39,139 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:00:39,139 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f377aa56a10>
2023-03-15 15:00:40,578 host.py INFO : Creating host esxi01.demo.local
2023-03-15 15:00:40,578 host.py INFO : Creating host esxi01.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi01:999701628:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 15:00:44,113 host.py INFO : The response is {'id': 'c43c7f17-a312-4cf7-8f05-021469e07259'}
2023-03-15 15:00:44,473 host.py INFO : Getting host c43c7f17-a312-4cf7-8f05-021469e07259 details
2023-03-15 15:00:44,818 host.py INFO : changed True
2023-03-15 15:00:45,221 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:00:45,221 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:00:45,221 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7ff107acaa10>
2023-03-15 15:00:45,642 host.py INFO : Creating host esxi02.demo.local
2023-03-15 15:00:45,642 host.py INFO : Creating host esxi02.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi02:380351444:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 15:00:47,130 host.py INFO : The response is {'id': '244ed6ee-7f67-4225-be2c-8928882e92f4'}
2023-03-15 15:00:47,437 host.py INFO : Getting host 244ed6ee-7f67-4225-be2c-8928882e92f4 details
2023-03-15 15:00:47,707 host.py INFO : changed True
2023-03-15 15:00:48,167 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:00:48,167 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:00:48,167 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7ff819036a10>
2023-03-15 15:00:48,426 host.py INFO : Creating host esxi03.demo.local
2023-03-15 15:00:48,426 host.py INFO : Creating host esxi03.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi03:2135904199:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 15:00:49,886 host.py INFO : The response is {'id': 'b95ee577-706c-42ae-9d04-2694ea4ce40c'}
2023-03-15 15:00:50,156 host.py INFO : Getting host b95ee577-706c-42ae-9d04-2694ea4ce40c details
2023-03-15 15:00:50,440 host.py INFO : changed True
2023-03-15 15:00:51,020 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:00:51,021 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:00:51,021 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fede12de9b0>
2023-03-15 15:00:52,413 hostgroup.py INFO : Creating host group esx_datastore
2023-03-15 15:00:52,414 hostgroup.py INFO : Creating host group esx_datastore with hosts ['c43c7f17-a312-4cf7-8f05-021469e07259']
2023-03-15 15:00:55,301 hostgroup.py INFO : the response is {'id': 'c20bf02f-3842-4e29-951a-c892f62bf212'}
2023-03-15 15:00:55,588 hostgroup.py INFO : Getting host group c20bf02f-3842-4e29-951a-c892f62bf212 details
2023-03-15 15:00:55,875 hostgroup.py INFO : changed True
2023-03-15 15:00:56,296 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:00:56,296 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:00:56,296 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f011d99e9b0>
2023-03-15 15:00:56,544 hostgroup.py INFO : Getting host group c20bf02f-3842-4e29-951a-c892f62bf212 details
2023-03-15 15:00:57,122 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 15:00:57,122 hostgroup.py INFO : existing hosts ['c43c7f17-a312-4cf7-8f05-021469e07259']
2023-03-15 15:00:57,122 hostgroup.py INFO : Adding hosts ['244ed6ee-7f67-4225-be2c-8928882e92f4'] to host group esx_datastore
2023-03-15 15:00:58,995 hostgroup.py INFO : Getting host group c20bf02f-3842-4e29-951a-c892f62bf212 details
2023-03-15 15:00:59,277 hostgroup.py INFO : changed True
2023-03-15 15:00:59,677 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:00:59,678 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:00:59,678 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f06b10869b0>
2023-03-15 15:00:59,977 hostgroup.py INFO : Getting host group c20bf02f-3842-4e29-951a-c892f62bf212 details
2023-03-15 15:01:00,571 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 15:01:00,571 hostgroup.py INFO : existing hosts ['c43c7f17-a312-4cf7-8f05-021469e07259', '244ed6ee-7f67-4225-be2c-8928882e92f4']
2023-03-15 15:01:00,571 hostgroup.py INFO : Adding hosts ['b95ee577-706c-42ae-9d04-2694ea4ce40c'] to host group esx_datastore
2023-03-15 15:01:03,487 hostgroup.py INFO : Getting host group c20bf02f-3842-4e29-951a-c892f62bf212 details
2023-03-15 15:01:03,812 hostgroup.py INFO : changed True
2023-03-15 15:01:04,422 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:01:04,422 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:01:04,422 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f248ceb2aa0>
2023-03-15 15:01:05,006 volume.py INFO : Creating volume esx_vol of size 858993459200 with performance policy None, protection_policy None, description DTW ESXi DataStore and volume_group None
2023-03-15 15:01:06,793 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 15:01:06,793 volume.py INFO : Mapping volume esx_vol to hostgroup esx_datastore with HLU None
2023-03-15 15:01:08,922 volume.py INFO : Getting volume snapshots
2023-03-15 15:22:58,801 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:22:58,801 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:22:58,802 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fe6cc0cab30>
2023-03-15 15:23:00,134 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 15:23:00,134 volume.py INFO : Volume esx_vol is already mapped to hostgroup esx_datastore
2023-03-15 15:23:00,808 volume.py INFO : Getting volume snapshots
2023-03-15 15:23:33,077 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:23:33,077 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:23:33,077 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7ff3dd822b30>
2023-03-15 15:23:33,780 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 15:23:33,780 volume.py INFO : Unmapping volume esx_vol from hostgroup esx_datastore
2023-03-15 15:23:35,818 volume.py INFO : Getting volume snapshots
2023-03-15 15:23:36,373 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:23:36,373 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:23:36,373 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f4fe107eb30>
2023-03-15 15:23:37,173 volume.py INFO : Deleting volume esx_vol 
2023-03-15 15:23:37,173 volume.py INFO : Deleting volume esx_vol
2023-03-15 15:23:38,352 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:23:38,352 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:23:38,352 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f513be16a10>
2023-03-15 15:23:38,645 hostgroup.py INFO : Getting host group c20bf02f-3842-4e29-951a-c892f62bf212 details
2023-03-15 15:23:38,987 hostgroup.py INFO : Deleting host group esx_datastore 
2023-03-15 15:23:40,739 hostgroup.py INFO : changed True
2023-03-15 15:23:41,350 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:23:41,351 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:23:41,351 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f4906b1ea70>
2023-03-15 15:23:41,745 host.py INFO : changed False
2023-03-15 15:23:42,132 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:23:42,132 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:23:42,132 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f59491eea70>
2023-03-15 15:23:42,524 host.py INFO : changed False
2023-03-15 15:23:42,923 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:23:42,924 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:23:42,924 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f2dd73c2a70>
2023-03-15 15:23:43,324 host.py INFO : changed False
2023-03-15 15:23:53,515 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:23:53,515 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:23:53,515 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f6a04b2ea70>
2023-03-15 15:23:54,242 host.py INFO : Creating host esxi01.demo.local
2023-03-15 15:23:54,242 host.py INFO : Creating host esxi01.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi01:999701628:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 15:23:58,801 host.py INFO : The response is {'id': '8eb66bfe-a8e1-4815-9c28-4fadfe055b71'}
2023-03-15 15:23:59,180 host.py INFO : Getting host 8eb66bfe-a8e1-4815-9c28-4fadfe055b71 details
2023-03-15 15:23:59,567 host.py INFO : changed True
2023-03-15 15:24:00,003 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:24:00,003 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:24:00,004 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fe8996b6a70>
2023-03-15 15:24:00,441 host.py INFO : Creating host esxi02.demo.local
2023-03-15 15:24:00,442 host.py INFO : Creating host esxi02.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi02:380351444:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 15:24:02,025 host.py INFO : The response is {'id': '9c7353bd-7b3e-4f5f-8350-cd0df6e0db5d'}
2023-03-15 15:24:02,321 host.py INFO : Getting host 9c7353bd-7b3e-4f5f-8350-cd0df6e0db5d details
2023-03-15 15:24:02,764 host.py INFO : changed True
2023-03-15 15:24:03,153 host.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:24:03,153 host.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:24:03,153 host.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7fb4de002a40>
2023-03-15 15:24:03,494 host.py INFO : Creating host esxi03.demo.local
2023-03-15 15:24:03,494 host.py INFO : Creating host esxi03.demo.local with initiators [{'port_name': 'iqn.1998-01.com.vmware:esxi03:2135904199:65', 'port_type': 'iSCSI', 'chap_single_username': None, 'chap_single_password': None, 'chap_mutual_username': None, 'chap_mutual_password': None}]
2023-03-15 15:24:05,088 host.py INFO : The response is {'id': '668de4b2-403b-4f2b-bcd0-6ff36ef7bdb6'}
2023-03-15 15:24:05,378 host.py INFO : Getting host 668de4b2-403b-4f2b-bcd0-6ff36ef7bdb6 details
2023-03-15 15:24:05,713 host.py INFO : changed True
2023-03-15 15:24:06,282 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:24:06,282 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:24:06,282 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f42ba2169e0>
2023-03-15 15:24:06,835 hostgroup.py INFO : Creating host group esx_datastore
2023-03-15 15:24:06,835 hostgroup.py INFO : Creating host group esx_datastore with hosts ['8eb66bfe-a8e1-4815-9c28-4fadfe055b71']
2023-03-15 15:24:09,921 hostgroup.py INFO : the response is {'id': '5eb128b4-f6b8-4eb1-b7cc-4b494ba78bae'}
2023-03-15 15:24:10,289 hostgroup.py INFO : Getting host group 5eb128b4-f6b8-4eb1-b7cc-4b494ba78bae details
2023-03-15 15:24:10,618 hostgroup.py INFO : changed True
2023-03-15 15:24:10,998 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:24:10,998 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:24:10,998 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f641889ea10>
2023-03-15 15:24:11,253 hostgroup.py INFO : Getting host group 5eb128b4-f6b8-4eb1-b7cc-4b494ba78bae details
2023-03-15 15:24:11,789 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 15:24:11,790 hostgroup.py INFO : existing hosts ['8eb66bfe-a8e1-4815-9c28-4fadfe055b71']
2023-03-15 15:24:11,790 hostgroup.py INFO : Adding hosts ['9c7353bd-7b3e-4f5f-8350-cd0df6e0db5d'] to host group esx_datastore
2023-03-15 15:24:13,695 hostgroup.py INFO : Getting host group 5eb128b4-f6b8-4eb1-b7cc-4b494ba78bae details
2023-03-15 15:24:14,245 hostgroup.py INFO : changed True
2023-03-15 15:24:14,622 hostgroup.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:24:14,622 hostgroup.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:24:14,622 hostgroup.py INFO : Got Python library connection instance for provisioning on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f96ec932a10>
2023-03-15 15:24:15,150 hostgroup.py INFO : Getting host group 5eb128b4-f6b8-4eb1-b7cc-4b494ba78bae details
2023-03-15 15:24:16,190 hostgroup.py INFO : Adding hosts to host group esx_datastore
2023-03-15 15:24:16,190 hostgroup.py INFO : existing hosts ['8eb66bfe-a8e1-4815-9c28-4fadfe055b71', '9c7353bd-7b3e-4f5f-8350-cd0df6e0db5d']
2023-03-15 15:24:16,190 hostgroup.py INFO : Adding hosts ['668de4b2-403b-4f2b-bcd0-6ff36ef7bdb6'] to host group esx_datastore
2023-03-15 15:24:19,012 hostgroup.py INFO : Getting host group 5eb128b4-f6b8-4eb1-b7cc-4b494ba78bae details
2023-03-15 15:24:19,270 hostgroup.py INFO : changed True
2023-03-15 15:24:19,860 volume.py INFO : HAS_PY4PS = True , IMPORT_ERROR = 
2023-03-15 15:24:19,860 volume.py INFO : IS_SUPPORTED_PY4PS_VERSION = True , VERSION_ERROR = 
2023-03-15 15:24:19,860 volume.py INFO : Got Py4Ps instance for provisioning and protection on PowerStore <PyPowerStore.powerstore_conn.PowerStoreConn object at 0x7f8bf2c8ab30>
2023-03-15 15:24:20,466 volume.py INFO : Creating volume esx_vol of size 858993459200 with performance policy None, protection_policy None, description DTW ESXi DataStore and volume_group None
2023-03-15 15:24:22,582 volume.py INFO : Current volume size 858993459200 B is same as 858993459200 B specified
2023-03-15 15:24:22,582 volume.py INFO : Mapping volume esx_vol to hostgroup esx_datastore with HLU None
2023-03-15 15:24:24,871 volume.py INFO : Getting volume snapshots
